image: node:latest

variables:
  NODE_ENV: ci

services:
  - mongo:latest
  - nats:latest
  - nats-streaming:latest

before_script:
  - npm ci

test:
 script:
   - node_modules/.bin/nyc npm test && node_modules/.bin/nyc report --reporter=text-lcov
