image: ubuntu:xenial

services:
  - mongo:latest
  - nats:latest
  - node:10

before_script:
  - npm ci

cache:
  paths:
    - node_modules/

test:
 script:
   - node_modules/.bin/nyc npm test && node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls
