image: node:lates

variables:
  NODE_ENV: ci

services:
  - mongo:latest
  - nats:latest
  - nats-streaming:latest

before_script:
  - npm ci

test:
  script:
    - node_modules/.bin/nyc npm test && node_modules/.bin/nyc report --reporter=text-lcov
  artifacts:
    paths:
      - .nyc_output/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv .nyc_output/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
