image: node:latest

variables:
  NODE_ENV: ci

services:
  - mongo:latest
  - nats:latest
  - nats-streaming:latest

before_script:
  - npm ci

test:
  script:
    - nyc --reporter=html npm test
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
